/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissionResponse } from '../../models/mission-response';

export interface AcceptMission$Params {
  missionId: number;
}

export function acceptMission(http: HttpClient, rootUrl: string, params: AcceptMission$Params, context?: HttpContext): Observable<StrictHttpResponse<MissionResponse>> {
  const rb = new RequestBuilder(rootUrl, acceptMission.PATH, 'put');
  if (params) {
    rb.path('missionId', params.missionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MissionResponse>;
    })
  );
}

acceptMission.PATH = '/api/missions/{missionId}/accept';
