/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DashboardStats } from '../models/dashboard-stats';
import { getStats } from '../fn/dashboard/get-stats';
import { GetStats$Params } from '../fn/dashboard/get-stats';

@Injectable({ providedIn: 'root' })
export class DashboardService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getStats()` */
  static readonly GetStatsPath = '/admin/dashboard/stats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStats$Response(params?: GetStats$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardStats>> {
    return getStats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStats(params?: GetStats$Params, context?: HttpContext): Observable<DashboardStats> {
    return this.getStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<DashboardStats>): DashboardStats => r.body)
    );
  }

}
