/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStatsResponse } from '../../models/user-stats-response';

export interface GetUserStats$Params {
}

export function getUserStats(http: HttpClient, rootUrl: string, params?: GetUserStats$Params, context?: HttpContext): Observable<StrictHttpResponse<UserStatsResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserStatsResponse>;
    })
  );
}

getUserStats.PATH = '/api/v1/users/me/stats';
