/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface NotificationMission {
  creationDate?: string;
  id?: number;
  lastModifiedDate?: string;
  message?: string;
  read?: boolean;
  title?: string;
  type?: 'MISSION_CREATED' | 'MISSION_ASSIGNED' | 'MISSION_UPDATED' | 'MISSION_COMPLETED' | 'MISSION_CANCELLED';
  user?: User;
}
