/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserStatsResponse {
  currentBadge?: string;
  hoursWorked?: number;
  missionsCompleted?: number;
  nextBadge?: string;
  points?: number;
  pointsToNextBadge?: number;
  progressPercentage?: number;
}
