/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
export interface User {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  badge?: 'NOVICE' | 'BEGINNER' | 'EXPLORER' | 'CHAMPION' | 'LEGEND';
  createdAt?: string;
  credentialsNonExpired?: boolean;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  gender?: 'MALE' | 'FEMALE';
  hourEffected?: number;
  id?: number;
  lastModifiedDate?: string;
  lastSeen?: string;
  lastname?: string;
  missionCompleted?: number;
  name?: string;
  password?: string;
  point?: number;
  roles?: Array<Role>;
  skill?: 'COMMUNICATION' | 'ORGANIZATION' | 'IT' | 'TEACHING' | 'FIRST_AID' | 'LOGISTICS' | 'PSYCHOLOGICAL_SUPPORT' | 'LEADERSHIP';
  statsSummary?: string;
  userOnline?: boolean;
  username?: string;
}
